/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import gestion.EscritorioPersonalizado;
import clases.Usuario;
import gestion.GestionCliente;
import gestion.GestionEmpleado;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Avril
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmPrincipal.class.getName());

    private EscritorioPersonalizado escritorio; 
    private GestionEmpleado gestionEmpleado = new GestionEmpleado();
    private GestionCliente gestionClientes = new GestionCliente();
    
    private Usuario usuario;


    public frmPrincipal(Usuario usuario) {
        initComponents();
        escritorio = new EscritorioPersonalizado();
        this.setContentPane(escritorio);
        this.usuario = usuario;
        cargarPermisos();
    }
    
    private void cargarPermisos(){
    
        if(usuario.getRol().equals("Administrador")){
            mnGestionEmpleados.setVisible(true);
            mnProyectosConstruccion.setVisible(true);
            mnClientesPotenciales.setVisible(true);
            mnVentas.setVisible(true);
            mnAyC.setVisible(true);
            mnSalir.setVisible(true);
        }
        else {
            if(usuario.getRol().equals("Asesor de Ventas")){
                mnGestionEmpleados.setVisible(true);
                mnProyectosConstruccion.setVisible(true);
                mnClientesPotenciales.setVisible(true);
                mnVentas.setVisible(true);
                mnAyC.setVisible(true);
                mnSalir.setVisible(true);
            }
            else{
                if(usuario.getRol().equals("Gerente")){
                    mnGestionEmpleados.setVisible(true);
                    mnProyectosConstruccion.setVisible(true);
                    mnClientesPotenciales.setVisible(true);
                     mnVentas.setVisible(true);
                    mnAyC.setVisible(true);
                    mnSalir.setVisible(true);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnGestionEmpleados = new javax.swing.JMenu();
        mnitmConsultarEmpleados = new javax.swing.JRadioButtonMenuItem();
        mnitmModificarEmpleados = new javax.swing.JRadioButtonMenuItem();
        mnProyectosConstruccion = new javax.swing.JMenu();
        mnitmConsultarDepartamentos = new javax.swing.JRadioButtonMenuItem();
        mnitmGestionarDepartamentos = new javax.swing.JRadioButtonMenuItem();
        mnClientesPotenciales = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        mnitmModificarClientes = new javax.swing.JRadioButtonMenuItem();
        mnVentas = new javax.swing.JMenu();
        mnitmConsultarVentas = new javax.swing.JRadioButtonMenuItem();
        mnitmGestionarVentas = new javax.swing.JRadioButtonMenuItem();
        mnAyC = new javax.swing.JMenu();
        mnSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnGestionEmpleados.setText("Gestion Empleados");

        mnitmConsultarEmpleados.setSelected(true);
        mnitmConsultarEmpleados.setText("Consultar empleados");
        mnGestionEmpleados.add(mnitmConsultarEmpleados);

        mnitmModificarEmpleados.setSelected(true);
        mnitmModificarEmpleados.setText("Modificar Empleados");
        mnGestionEmpleados.add(mnitmModificarEmpleados);

        jMenuBar1.add(mnGestionEmpleados);

        mnProyectosConstruccion.setText("Proyectos de Construccion");
        mnProyectosConstruccion.setActionCommand("Proyectos de ConstruccionProyectos de Construccion");

        mnitmConsultarDepartamentos.setSelected(true);
        mnitmConsultarDepartamentos.setText("Consultar Departamentos");
        mnProyectosConstruccion.add(mnitmConsultarDepartamentos);

        mnitmGestionarDepartamentos.setSelected(true);
        mnitmGestionarDepartamentos.setText("Gestionar Departamentos");
        mnProyectosConstruccion.add(mnitmGestionarDepartamentos);

        jMenuBar1.add(mnProyectosConstruccion);

        mnClientesPotenciales.setText("Gestion Clientes Potenciales");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Consultar Clientes");
        mnClientesPotenciales.add(jRadioButtonMenuItem1);

        mnitmModificarClientes.setSelected(true);
        mnitmModificarClientes.setText("Modificar Clientes");
        mnClientesPotenciales.add(mnitmModificarClientes);

        jMenuBar1.add(mnClientesPotenciales);

        mnVentas.setText("Ventas");

        mnitmConsultarVentas.setSelected(true);
        mnitmConsultarVentas.setText("Consultar Ventas");
        mnVentas.add(mnitmConsultarVentas);

        mnitmGestionarVentas.setSelected(true);
        mnitmGestionarVentas.setText("Gestionar Ventas");
        mnVentas.add(mnitmGestionarVentas);

        jMenuBar1.add(mnVentas);

        mnAyC.setText("Acabados y Opcionales Disponibles");
        jMenuBar1.add(mnAyC);

        mnSalir.setText("Salir");
        jMenuBar1.add(mnSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal(new Usuario( "",  "",  "")).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JMenu mnAyC;
    private javax.swing.JMenu mnClientesPotenciales;
    private javax.swing.JMenu mnGestionEmpleados;
    private javax.swing.JMenu mnProyectosConstruccion;
    private javax.swing.JMenu mnSalir;
    private javax.swing.JMenu mnVentas;
    private javax.swing.JRadioButtonMenuItem mnitmConsultarDepartamentos;
    private javax.swing.JRadioButtonMenuItem mnitmConsultarEmpleados;
    private javax.swing.JRadioButtonMenuItem mnitmConsultarVentas;
    private javax.swing.JRadioButtonMenuItem mnitmGestionarDepartamentos;
    private javax.swing.JRadioButtonMenuItem mnitmGestionarVentas;
    private javax.swing.JRadioButtonMenuItem mnitmModificarClientes;
    private javax.swing.JRadioButtonMenuItem mnitmModificarEmpleados;
    // End of variables declaration//GEN-END:variables
}
